### ISSUE TITLE
Error in atexit._run_exitfuncs when running in Windows 10

### ISSUE THREAD

**Issue by yangliu2** [IndicoDataSolutions/finetune#212]
**Describe the bug**
Problem deleting temp file while running in Windows 10. 
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\yang.liu\AppData\Local\conda\conda\envs\python36\lib\site-packages\finetune\base.py", line 537, in __del__
    shutil.rmtree(file_or_folder)
  File "C:\Users\yang.liu\AppData\Local\conda\conda\envs\python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\yang.liu\AppData\Local\conda\conda\envs\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\yang.liu\AppData\Local\conda\conda\envs\python36\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\yang.liu\AppData\Local\conda\conda\envs\python36\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\yang.liu\\AppData\\Local\\Temp\\Finetunerxoy0m5o\\eval'
```
after running this code:
```
def train(X_train, Y_train):
    model = Classifier()
    model.fit(X_train, Y_train)
    print('trained model')
    out_dir = os.path.join('models', 'finetune.model')
    model.save(out_dir)
    return model
```

**Expected behavior**
Expected to delete the temp file if run as administrator

**Additional context**
Please don't ask why I use Windows. I know Linux works.

**Comment by madisonmay** [comment]
Thanks for the bug report!  It does seem like a windows specific error but I think we can work around it by using something like:

```
        ignore_errors = (sys.platform == 'win32')
        shutil.rmtree(self.tmpdir, ignore_errors=ignore_errors)
```

**Comment by yangliu2** [comment]
Thanks! It's not a breaking bug. The trained model works as intended. More of an annoyance really.

**Comment by madisonmay** [comment]
https://github.com/IndicoDataSolutions/finetune/pull/215
