### ISSUE TITLE
Error in prediction using CPU from model trained with GPUs

### ISSUE THREAD

**Issue by natuan** [IndicoDataSolutions/finetune#274]
**Describe the bug**
I'm not sure if this is a bug or simply has not been supported right now. I had a Comparison model trained using GPUs, and then I used it to make prediction on a machine that has no GPUs. I got the `KeyError: 'per_process_gpu_memory_fraction'` with the following stack trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/target_models/comparison.py", line 72, in predict_proba
    return BaseModel.predict_proba(self, pairs)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 399, in predict_proba
    raw_probas = self._predict_proba(*args, **kwargs)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 392, in _predict_proba
    raw_preds = self._inference(Xs, PredictMode.PROBAS)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 364, in _inference
    estimator, hooks = self.get_estimator()
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 254, in get_estimator
    self.config.per_process_gpu_memory_fraction
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/config.py", line 175, in __getattr__
    return self[attr]
KeyError: 'per_process_gpu_memory_fraction'

**Minimum Reproducible Example**
Assuming 'foo' is is a model trained with GPUs, the following steps should reproduce the above error:
`model = Comparison.load('foo')`
`model.predict_proba([('Information Security', 'Business Analyst')])`

**Expected behavior**
The model should be used during inference, possibly after specifying some options. I looked at the configuration settings but I couldn't find a solution.

**Additional context**
The model was trained with AWS instances; I could probably give specific information about the GPUs if that's helpful. The machine to run inference is macOS Mojave.

**Comment by benleetownsend** [comment]
Thank you for the bug report. I believe that this is actually caused by training and inference being run on different versions of finetune. For now, if you can try to downgrade the version of finetune you are running on the mac to the same as was used for training. (probably 0.6.2 based on the error message) and let me know if this solves the problem.

**Comment by natuan** [comment]
Thank you for the hint. I confirm that after downgrading to 0.6.2, I could do the inference on the machine without GPUs.
