### ISSUE TITLE
Cannot download GPT2Large

### ISSUE THREAD

**Issue by khoa-ho** [IndicoDataSolutions/finetune#372]
**Describe the bug**
The link to `GPT2Large` model seems broken.

**Minimum Reproducible Example**
```
>>> from finetune import Classifier
>>> from finetune.base_models import GPT2Large
>>> model = Classifier(base_model=GPT2Large)
Downloading: model-lg.jl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/finetune/target_models/classifier.py", line 67, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/finetune/base.py", line 76, in __init__
    download_data_if_required(self.config.base_model)
  File "/usr/local/lib/python3.6/dist-packages/finetune/util/download.py", line 22, in download_data_if_required
    data = urllib.request.urlopen(file_obj['url']).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
or
```
wget https://s3.amazonaws.com/bendropbox/gpt2/model-lg.jl
--2019-08-31 03:28:42--  https://s3.amazonaws.com/bendropbox/gpt2/model-lg.jl
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.186.93
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.186.93|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-31 03:28:43 ERROR 403: Forbidden.
```

**Expected behavior**
Model weight downloaded normally like `GPT2Medium` or `GPT2`

**Comment by madisonmay** [comment]
@khoa-ho apologies!  Link should work now -- was a permissions issue.
