### ISSUE TITLE
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_3' with dtype float

### ISSUE THREAD

**Issue by tingkai-zhang** [IndicoDataSolutions/finetune#41]
**Describe the bug**

```
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_3' with dtype float
	 [[Node: Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: Mean_3/_943 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3032_Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model.fit(train_X, train_y)
  File "/home/tingkai/finetune/finetune/lm_base.py", line 169, in fit
    return self.finetune(*args, **kwargs)
  File "/home/tingkai/finetune/finetune/lm_classifier.py", line 47, in finetune
    return self._finetune(X, Y=Y, batch_size=batch_size)
  File "/home/tingkai/finetune/finetune/lm_base.py", line 130, in _finetune
    summary = self.sess.run(self.summaries, {self.X: xmb, self.M: mmb, self.Y: ymb})
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_3' with dtype float
	 [[Node: Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: Mean_3/_943 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3032_Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_3', defined at:
  File "test.py", line 18, in <module>
    model.fit(train_X, train_y)
  File "/home/tingkai/finetune/finetune/lm_base.py", line 169, in fit
    return self.finetune(*args, **kwargs)
  File "/home/tingkai/finetune/finetune/lm_classifier.py", line 47, in finetune
    return self._finetune(X, Y=Y, batch_size=batch_size)
  File "/home/tingkai/finetune/finetune/lm_base.py", line 111, in _finetune
    self._build_model(n_updates_total=n_updates_total, target_dim=self.target_dim)
  File "/home/tingkai/finetune/finetune/lm_base.py", line 357, in _build_model
    self._construct_graph(n_updates_total, target_dim, train=train)
  File "/home/tingkai/finetune/finetune/lm_base.py", line 277, in _construct_graph
    self._define_placeholders()
  File "/home/tingkai/finetune/finetune/lm_base.py", line 386, in _define_placeholders
    self.do_dropout = tf.placeholder(tf.float32)  # 1 for do dropout and 0 to not do dropout
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4848, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/tingkai/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_3' with dtype float
	 [[Node: Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: Mean_3/_943 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3032_Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Minimum Reproducible Example**

I was running the example code with my own data.
train_X is a list of string,
train_y is numpy array of int label
```
model = LanguageModelClassifier()
model.fit(train_X, train_y)
predictions = model.predict(test_X)
model.save('test_model/model_0') 
```

**Expected behavior**

**Additional context**

**Comment by madisonmay** [comment]
Hi @tingkai-zhang -- I just merged a patch for your issue.  Please let me know if the issue persists.  Thanks for the report!
